Feature/filter for test patients
uwcirg/cosri-patientsearch pull request #192
Opened 2023-08-02 17:18 UTC by achen2401

https://www.pivotaltracker.com/story/show/185649710

- A new environment variable, `ENABLE_FILTER_FOR_TEST_PATIENTS`, is used to determine whether to show the checkbox for test patients.
- A new environment variable, `FILTER_FOR_TEST_PATIENTS_LABEL`, is used to label the checkbox for filtering for test patients, e.g. `FILTER_FOR_TEST_PATIENTS_LABEL=Test recipients` for ISACC
- Test patients will be hidden by default

Screenshot of the UI
![Screen Shot 2023-08-02 at 10 06 14 AM](https://github.com/uwcirg/cosri-patientsearch/assets/12942714/6759fabf-f0c9-425d-baba-80b61c83fe29)

2023-08-02 19:09 UTC, mcjustin approved these changes
Thanks for the quick work @achen2401 ! Perhaps we should switch to this branch for testing on dev...

2023-08-02 22:12 UTC, mcjustin requested changes
@achen2401  now that I see this live on the dev system, I realize that I didn't spec it out very well at https://www.pivotaltracker.com/story/show/185649710 .
Can you please make these changes?
1. Change the checkbox label "Test recipients" to "Include test recipients"
2. When the checkbox is checked, it should include all recipients, whether they are test or not.
3. Move the above checkbox & label to be underneath the "Recipients I am following" checkbox (low priority, ok to skip if it's complicated)

2023-08-02 23:07 UTC, achen2401 commented
> Can you please make these changes?
> 
> 1. Change the checkbox label "Test recipients" to "Include test recipients"
> 2. When the checkbox is checked, it should include all recipients, whether they are test or not.
> 3. Move the above checkbox & label to be underneath the "Recipients I am following" checkbox (low priority, ok to skip if it's complicated)

@mcjustin 2, 3 are now on shared dev instance.  For 1.  we just need to change the environment var, `FILTER_FOR_TEST_PATIENTS_LABEL` to say `Include test patients`

2023-08-02 23:32 UTC, mcjustin commented
> @mcjustin 2, 3 are now on shared dev instance. For 1. we just need to change the environment var, `FILTER_FOR_TEST_PATIENTS_LABEL` to say `Include test patients`

@achen2401  this looks great to me now (ack the label still needs to be configured), merge when ready!

2023-08-02 23:33 UTC, mcjustin approved these changes

2023-08-03 16:46 UTC, pbugni approved these changes

2023-08-03 16:46 UTC, pbugni commented on patientsearch/config.py
> +    "FILTER_FOR_TEST_PATIENTS_LABEL", "Include test patients"
I updated just now on isacc-dev, but think this config is overkill, seems that we've settled on a good value and as we know, less config, is more ;)

2023-08-03 16:46 UTC, pbugni commented on patientsearch/src/js/components/PatientListTable.js
> +        apiURL += `&_security:not=HTEST`;
ah, so nice and clean, in the end :)

2023-08-03 21:05 UTC, merged