add last accessed column on UI
uwcirg/cosri-patientsearch pull request #73
Opened 2021-09-28 00:48 UTC by achen2401

https://www.pivotaltracker.com/story/show/179725843
Add the "Last Accessed" column on the patient search UI
the column is populated by `patient.meta.lastupdated` field

2021-09-28 21:44 UTC, pbugni approved these changes

2021-09-28 23:14 UTC, pbugni requested changes

2021-09-28 23:14 UTC, pbugni commented on patientsearch/src/js/components/PatientListTable.js
> +    if (data.id) return `${dataURL}/${data.id}`;
@achen2401 we need to include `/external_search` ONLY when data.id is not present.  Actually, it's more complicated - we need to include /external_search anytime we don't have `data.id` or we don't have the identifier you use to paint some rows white.

2021-09-30 20:23 UTC, achen2401 commented
@pbugni @ivan-c this is ready for you to review when you have a minute.

2021-09-30 20:26 UTC, pbugni approved these changes

2021-09-30 20:29 UTC, ivan-c approved these changes

2021-09-30 20:31 UTC, merged